language: php

php:
  - 5.6

install:
  - composer install --dev --no-interaction

script:
  - phpunit --verbose --tap --coverage-clover build/logs/clover.xml

after_script:
  - bash bin/codeclimate.sh
